enum AppLanguage { en, ja }

class AppStrings {
  AppStrings._();

  static const Map<AppLanguage, Map<String, String>> localizedValues = {
    AppLanguage.en: {
      'app_title': 'Tokyo Car Club',
      'home_title': 'Rent your dream car',
      'subtitle': 'Premium car rental in Tokyo',
      'pick_up_location': 'Pick-up location',
      'drop_off_location': 'Drop-off location',
      'pick_up_date': 'Pick-up date',
      'drop_off_date': 'Drop-off date',
      'search_cars': 'Search Cars',
      'loading': 'Loading...',
      'language': 'Language',
      'theme': 'Theme',
      'light_theme': 'Light',
      'dark_theme': 'Dark',
      'car_type': 'Car type',
      'economy': 'Economy',
      'suv': 'SUV',
      'luxury': 'Luxury',
      'booking_confirmed': 'Your Booking is Confirmed',
      'booking_details_sent': 'We\'ve sent details to your email & SMS',
      'view_my_bookings': 'View My Bookings',
      'my_bookings': 'My Bookings',
      'upcoming': 'Upcoming',
      'ongoing': 'Ongoing',
      'completed': 'Completed',
      'cancelled': 'Cancelled',
      'view_details': 'View Details',
      'booking_details': 'Booking Details',
      'booking_id': 'Booking ID',
      'pickup_location': 'Pickup Location',
      'dropoff_location': 'Drop-off Location',
      'payment_mode': 'Payment Mode',
      'download_invoice': 'Download Invoice',
      'location_map': 'Location Map',
      'tap_to_view_map': 'Tap to view on map',
      'home': 'Home',
      'explore': 'Explore',
      'bookings': 'Bookings',
      'saved': 'Saved',
      'profile': 'Profile',
      'mumbai_india': 'Mumbai, India',
      'search_placeholder': 'Search for cars, brands, or types',
      'discount_20': '-20% OFF',
      'bmw_m2': 'BMW M2 Competition',
      'popular_cars': 'Popular Cars',
      'audi_a6': 'Audi A6 Sedan',
      'rating_48': '4.8',
      'price_per_day': '₹4,200 / day',
      'view': 'View',
      'bmw_5_series': 'BMW 5 Series',
      'reviews_120': '4.8 (120 Reviews)',
      'seats_5': '5 Seats',
      'bags_2': '2 Bags',
      'automatic': 'Automatic',
      'petrol': 'Petrol',
      'bmw_description': 'The BMW 5 Series offers luxury, comfort, and performance with a powerful engine, premium interiors, and advanced safety features.',
      'availability': 'Availability',
      'select_date': 'Select Date',
      'select_time': 'Select Time',
      'price_4500_day': '₹4,500 / day',
      'deposit_10000': 'Deposit: ₹10,000',
      'continue_booking': 'Continue to Booking',
      'invoice_downloaded': 'Invoice downloaded',
      'booking_summary': 'Booking Summary',
      'car_details': 'Car Details',
      'luxury_sedan_auto_petrol': 'Luxury Sedan • Automatic • Petrol',
      'pickup_date_time': 'Pickup Date & Time',
      'dropoff_date_time': 'Drop-off Date & Time',
      'pickup_location_text': 'Pickup Location',
      'mumbai_airport_t2': 'Mumbai Airport T2',
      'map_view': 'Map View',
      'total_fare': 'Total Fare',
      'car_rental_2_days': 'Car Rental (2 days)',
      'taxes_fees': 'Taxes & Fees',
      'insurance': 'Insurance',
      'total': 'Total',
      'insurance_optional': 'Insurance (Optional)',
      'comprehensive_insurance': 'Comprehensive Insurance Coverage',
      'payment_method': 'Payment Method',
      'credit_debit_card': 'Credit/Debit Card',
      'upi': 'UPI',
      'wallet': 'Wallet',
      'cash_at_pickup': 'Cash at Pickup',
      'proceed_to_payment': 'Proceed to Payment',
      'saved_cars': 'Saved Cars',
      'car_brands': 'Car Brands',
      'car_types': 'Car Types',
      'popular_locations': 'Popular Locations',
      'special_offer': 'SPECIAL OFFER',
      'get_30_off': 'Get 30% OFF',
      'luxury_cars_weekend': 'On luxury cars this weekend',
      'tokyo_station': 'Tokyo Station',
      'shibuya': 'Shibuya',
      'harajuku': 'Harajuku',
      'cars_120': '120+ cars',
      'cars_85': '85+ cars',
      'cars_95': '95+ cars',
      'user_name': 'John Doe',
      'user_email': 'john.doe@email.com',
      'edit_profile': 'Edit Profile',
      'payment_methods': 'Payment Methods',
      'help_center': 'Help Center',
      'support': 'Support',
      'logout': 'Logout',
      'logout_confirmation': 'Are you sure you want to logout?',
      'cancel': 'Cancel',
      'name': 'Name',
      'email': 'Email',
      'phone': 'Phone',
      'save': 'Save',
      'change_photo': 'Change Photo',
      'profile_updated': 'Profile updated successfully',
      'notifications': 'Notifications',
      'no_notifications': 'No notifications yet',
      'booking_issue': 'Booking Issue',
      'payment_problem': 'Payment Problem',
      'car_location': 'Car Location',
      'general_inquiry': 'General Inquiry',
      'type_message': 'Type a message...',
      'settings': 'Settings',
      'dark_mode': 'Dark Mode',
      'change_password': 'Change Password',
      'privacy_policy': 'Privacy Policy',
      'delete_account': 'Delete Account',
      'select_language': 'Select Language',
      'change_password_message': 'You will be redirected to change your password',
      'delete_account_warning': 'This action cannot be undone. All your data will be permanently deleted.',
      'change': 'Change',
      'delete': 'Delete',
    },
    AppLanguage.ja: {
      'app_title': '東京カー クラブ',
      'home_title': '憧れの車をレンタル',
      'subtitle': '東京でプレミアムレンタカー',
      'pick_up_location': 'ピックアップ場所',
      'drop_off_location': '返却場所',
      'pick_up_date': 'ピックアップ日',
      'drop_off_date': '返却日',
      'search_cars': '車を検索',
      'loading': '読み込み中...',
      'language': '言語',
      'theme': 'テーマ',
      'light_theme': 'ライト',
      'dark_theme': 'ダーク',
      'car_type': '車タイプ',
      'economy': 'エコノミー',
      'suv': 'SUV',
      'luxury': 'ラグジュアリー',
      'booking_confirmed': '予約が確定しました',
      'booking_details_sent': 'メールとSMSで詳細をお送りしました',
      'view_my_bookings': '予約を見る',
      'my_bookings': '予約一覧',
      'upcoming': '予定',
      'ongoing': '進行中',
      'completed': '完了',
      'cancelled': 'キャンセル',
      'view_details': '詳細を見る',
      'booking_details': '予約詳細',
      'booking_id': '予約ID',
      'pickup_location': 'ピックアップ場所',
      'dropoff_location': '返却場所',
      'payment_mode': '支払い方法',
      'download_invoice': '請求書ダウンロード',
      'location_map': 'ロケーションマップ',
      'tap_to_view_map': 'マップで表示するにはタップ',
      'home': 'ホーム',
      'explore': '探索',
      'bookings': '予約',
      'saved': '保存済み',
      'profile': 'プロフィール',
      'mumbai_india': 'ムンバイ、インド',
      'search_placeholder': '車、ブランド、タイプで検索',
      'discount_20': '-20% オフ',
      'bmw_m2': 'BMW M2 コンペティション',
      'popular_cars': '人気の車',
      'audi_a6': 'アウディ A6 セダン',
      'rating_48': '4.8',
      'price_per_day': '₹4,200 / 日',
      'view': '表示',
      'bmw_5_series': 'BMW 5 シリーズ',
      'reviews_120': '4.8 (120 レビュー)',
      'seats_5': '5 席',
      'bags_2': '2 バッグ',
      'automatic': 'オートマチック',
      'petrol': 'ガソリン',
      'bmw_description': 'BMW 5シリーズは、パワフルなエンジン、プレミアムインテリア、高度な安全機能で高級、快適、パフォーマンスを提供します。',
      'availability': '利用可能性',
      'select_date': '日付を選択',
      'select_time': '時間を選択',
      'price_4500_day': '₹4,500 / 日',
      'deposit_10000': '保証金: ₹10,000',
      'continue_booking': '予約を続ける',
      'invoice_downloaded': '請求書をダウンロードしました',
      'booking_summary': '予約概要',
      'car_details': '車の詳細',
      'luxury_sedan_auto_petrol': 'ラグジュアリーセダン • オートマチック • ガソリン',
      'pickup_date_time': 'ピックアップ日時',
      'dropoff_date_time': '返却日時',
      'pickup_location_text': 'ピックアップ場所',
      'mumbai_airport_t2': 'ムンバイ空港 T2',
      'map_view': 'マップビュー',
      'total_fare': '合計料金',
      'car_rental_2_days': 'レンタカー (2日)',
      'taxes_fees': '税金・手数料',
      'insurance': '保険',
      'total': '合計',
      'insurance_optional': '保険 (オプション)',
      'comprehensive_insurance': '総合保険カバレッジ',
      'payment_method': '支払い方法',
      'credit_debit_card': 'クレジット/デビットカード',
      'upi': 'UPI',
      'wallet': 'ウォレット',
      'cash_at_pickup': 'ピックアップ時現金払い',
      'proceed_to_payment': '支払いに進む',
      'saved_cars': '保存された車',
      'car_brands': 'カーブランド',
      'car_types': '車種',
      'popular_locations': '人気の場所',
      'special_offer': 'スペシャルオファー',
      'get_30_off': '30%オフ',
      'luxury_cars_weekend': '週末の高級車',
      'tokyo_station': '東京駅',
      'shibuya': '渋谷',
      'harajuku': '原宿',
      'cars_120': '120台以上',
      'cars_85': '85台以上',
      'cars_95': '95台以上',
      'user_name': '田中太郎',
      'user_email': 'tanaka@email.com',
      'edit_profile': 'プロフィール編集',
      'payment_methods': '支払い方法',
      'help_center': 'ヘルプセンター',
      'support': 'サポート',
      'logout': 'ログアウト',
      'logout_confirmation': 'ログアウトしますか？',
      'cancel': 'キャンセル',
      'name': '名前',
      'email': 'メール',
      'phone': '電話番号',
      'save': '保存',
      'change_photo': '写真を変更',
      'profile_updated': 'プロフィールが更新されました',
      'notifications': '通知',
      'no_notifications': '通知はありません',
      'booking_issue': '予約の問題',
      'payment_problem': '支払いの問題',
      'car_location': '車の場所',
      'general_inquiry': '一般的なお問い合わせ',
      'type_message': 'メッセージを入力...',
      'settings': '設定',
      'dark_mode': 'ダークモード',
      'change_password': 'パスワード変更',
      'privacy_policy': 'プライバシーポリシー',
      'delete_account': 'アカウント削除',
      'select_language': '言語選択',
      'change_password_message': 'パスワード変更画面にリダイレクトされます',
      'delete_account_warning': 'この操作は元に戻せません。すべてのデータが完全に削除されます。',
      'change': '変更',
      'delete': '削除',
    },
  };
}
